language: en,en-GB
allowCompoundWords: true
ignoreRandomStrings: true
words:
  - astrovim
  - augroup
  - autocmd
  - autocmds
  - basedpyright
  - bashls
  - cips
  - clangd
  - cnaps
  - cssls
  - dkmoonfruit
  - dmalloc
  - dnsctl
  - dockerls
  - eip
  - elif
  - env
  - envrc
  - esac
  - esqlc
  - fakeip
  - ghostty
  - gingkoo
  - gitee
  - gitmodules
  - gofumpt
  - goimports
  - gomodifytags
  - gopls
  - gpms
  - graalvm
  - groovyls
  - heiyu
  - inreplace
  - jdbc
  - jsonls
  - ktlint
  - lazyvim
  - lspconfig
  - lualine
  - lzc
  - maven
  - mcpserver
  - moonfruit
  - mybatis
  - nanocloud
  - noremap
  - npmjs
  - nvim
  - nvimtools
  - oradb
  - pcre
  - plaintex
  - pyright
  - qwen
  - rubocop
  - setaf
  - shfmt
  - shopt
  - sonoma
  - swiftc
  - taplo
  - tavily
  - temurin
  - tput
  - tunnelblick
  - typst
  - venv
  - xctoolchain
  - xipcloud
  - yamlls
  - yanky
